ss_x=240
ss_y=45
offset_ss_x=0
offset_ss_y=20
offset_ssl_x=0
offset_ssl_y=18

offset_x_col2=90

self.curvetracer1 = QtWidgets.QLineEdit(self)
self.curvetracer1.setText("1")
self.curvetracer1.setGeometry(ss_x, offset_ss_y+ss_y, 60, 20)
self.curvetracer1_label=QtWidgets.QLabel('+ve voltage\n max (V)', self)
self.curvetracer1_label.setGeometry(ss_x, offset_ssl_y+ss_y-25, 140, 30)
self.curvetracer1.hide()
self.curvetracer1_label.hide()

self.curvetracer2 = QtWidgets.QLineEdit(self)
self.curvetracer2.setText("1")
self.curvetracer2.setGeometry(ss_x, offset_ss_y+ss_y*2, 60, 20)
self.curvetracer2_label=QtWidgets.QLabel('-ve voltage\n max (V)', self)
self.curvetracer2_label.setGeometry(ss_x, offset_ssl_y+(ss_y*2)-25, 140, 30)
self.curvetracer2.hide()
self.curvetracer2_label.hide()

self.curvetracer3 = QtWidgets.QLineEdit(self)
self.curvetracer3.setText("0.05")
self.curvetracer3.setGeometry(ss_x, offset_ss_y+ss_y*3, 60, 20)
self.curvetracer3_label=QtWidgets.QLabel('Voltage step (V)', self)
self.curvetracer3_label.setGeometry(ss_x, offset_ssl_y+(ss_y*3)-15, 100, 20)
self.curvetracer3.hide()
self.curvetracer3_label.hide()

self.curvetracer4 = QtWidgets.QLineEdit(self)
self.curvetracer4.setText("0.05")
self.curvetracer4.setGeometry(ss_x, offset_ss_y+ss_y*4, 60, 20)
self.curvetracer4_label=QtWidgets.QLabel('Start voltage (V)', self)
self.curvetracer4_label.setGeometry(ss_x, offset_ssl_y+(ss_y*4)-15, 100, 20)
self.curvetracer4.hide()
self.curvetracer4_label.hide()

self.curvetracer5 = QtWidgets.QLineEdit(self)
self.curvetracer5.setText("50")
self.curvetracer5.setGeometry(ss_x, offset_ss_y+ss_y*5, 60, 20)
self.curvetracer5_label=QtWidgets.QLabel('Step width (ms)', self)
self.curvetracer5_label.setGeometry(ss_x, offset_ssl_y+(ss_y*5)-15, 100, 20)
self.curvetracer5.hide()
self.curvetracer5_label.hide()

self.curvetracer6 = QtWidgets.QLineEdit(self)
self.curvetracer6.setText("1")
self.curvetracer6.setGeometry(ss_x, offset_ss_y+ss_y*6, 60, 20)
self.curvetracer6_label=QtWidgets.QLabel('Cycles', self)
self.curvetracer6_label.setGeometry(ss_x, offset_ssl_y+(ss_y*6)-15, 100, 20)
self.curvetracer6.hide()
self.curvetracer6_label.hide()

self.curvetracer7 = QtWidgets.QLineEdit(self)
self.curvetracer7.setText("10")
self.curvetracer7.setGeometry(ss_x+offset_x_col2, offset_ss_y+ss_y*1, 60, 20)
self.curvetracer7_label=QtWidgets.QLabel('Interpulse (ms)', self)
self.curvetracer7_label.setGeometry(ss_x+offset_x_col2, offset_ssl_y+(ss_y*1)-15, 100, 20)
self.curvetracer7.hide()
self.curvetracer7_label.hide()

self.curvetracer8 = QtWidgets.QLineEdit(self)
self.curvetracer8.setText("0")
self.curvetracer8.setGeometry(ss_x+offset_x_col2, offset_ss_y+ss_y*2, 60, 20)
self.curvetracer8_label=QtWidgets.QLabel('+ve current\n cut-off (uA)', self)
self.curvetracer8_label.setGeometry(ss_x+offset_x_col2, offset_ssl_y+(ss_y*2)-25, 140, 30)
self.curvetracer8.hide()
self.curvetracer8_label.hide()

self.curvetracer9 = QtWidgets.QLineEdit(self)
self.curvetracer9.setText("0")
self.curvetracer9.setGeometry(ss_x+offset_x_col2, offset_ss_y+ss_y*3, 60, 20)
self.curvetracer9_label=QtWidgets.QLabel('-ve current\n cut-off (uA)', self)
self.curvetracer9_label.setGeometry(ss_x+offset_x_col2, offset_ssl_y+(ss_y*3)-25, 140, 30)
self.curvetracer9.hide()
self.curvetracer9_label.hide()

self.curvetracer_combo1 = QtWidgets.QComboBox(self)
self.curvetracer_combo1.addItem('Staircase', 1)
self.curvetracer_combo1.addItem('Pulsed', -1)
self.curvetracer_combo1.setGeometry(ss_x+offset_x_col2, offset_ss_y+ss_y*4, 100, 20)
self.curvetracer_combo1_label=QtWidgets.QLabel('Bias type', self)
self.curvetracer_combo1_label.setGeometry(ss_x+offset_x_col2, offset_ssl_y+(ss_y*4)-15, 100, 20)
self.curvetracer_combo1.hide()
self.curvetracer_combo1_label.hide()

self.curvetracer_combo2 = QtWidgets.QComboBox(self)
self.curvetracer_combo2.addItem('Start towards V+', 1)
self.curvetracer_combo2.addItem('Start towards V-', -1)
self.curvetracer_combo2.addItem('Only V+', 1)
self.curvetracer_combo2.addItem('Only V-', -1)
self.curvetracer_combo2.setGeometry(ss_x+offset_x_col2, offset_ss_y+ss_y*5, 100, 20)
self.curvetracer_combo2_label=QtWidgets.QLabel('I-V span', self)
self.curvetracer_combo2_label.setGeometry(ss_x+offset_x_col2, offset_ssl_y+(ss_y*5)-15, 100, 20)
self.curvetracer_combo2.hide()
self.curvetracer_combo2_label.hide()

self.CB_curvetracer1 = QtWidgets.QCheckBox(self)
self.CB_curvetracer1.setChecked(False)
self.CB_curvetracer1.setGeometry(QtCore.QRect(ss_x+offset_x_col2, offset_ss_y+(ss_y*6)-20, 100, 20))
self.CB_curvetracer1_label=QtWidgets.QLabel('Halt and Return', self)
self.CB_curvetracer1_label.setGeometry(ss_x+offset_x_col2+15, offset_ss_y+(ss_y*6)-25, 100, 30)
self.CB_curvetracer1.hide()
self.CB_curvetracer1_label.hide()

self.CB_curvetracer2 = QtWidgets.QCheckBox(self)
self.CB_curvetracer2.setChecked(False)
self.CB_curvetracer2.setGeometry(QtCore.QRect(ss_x+offset_x_col2, offset_ss_y+(ss_y*7)-20, 100, 20))
self.CB_curvetracer2_label=QtWidgets.QLabel('CT Loop Step (V)', self)
self.CB_curvetracer2_label.setGeometry(ss_x+offset_x_col2+15, offset_ss_y+(ss_y*7)-25, 100, 30)
self.CB_curvetracer2.hide()
self.CB_curvetracer2_label.hide()

self.curvetracer10 = QtWidgets.QLineEdit(self)
self.curvetracer10.setText("1")
self.curvetracer10.setGeometry(QtCore.QRect(ss_x+offset_x_col2, offset_ss_y+ss_y*8, 60, 20))
self.curvetracer10_label=QtWidgets.QLabel('CT step', self)
self.curvetracer10_label.setGeometry(ss_x+offset_x_col2+15, offset_ss_y+(ss_y*8)-25, 100, 30)
self.curvetracer10.hide()
self.curvetracer10_label.hide()