ss_x=240
ss_y=35
offset_ss_x=0
offset_ss_y=20
offset_ssl_x=0
offset_ssl_y=18

self.form_finder1 = QtWidgets.QLineEdit(self)
self.form_finder1.setText("0.25")
self.form_finder1.setGeometry(ss_x, offset_ss_y+ss_y, 60, 20)
self.form_finder1_label=QtWidgets.QLabel('Voltage min (V)', self)
self.form_finder1_label.setGeometry(ss_x, offset_ssl_y+ss_y-15, 100, 20)
self.form_finder1.hide()
self.form_finder1_label.hide()

self.form_finder2 = QtWidgets.QLineEdit(self)
self.form_finder2.setText("0.25")
self.form_finder2.setGeometry(ss_x, offset_ss_y+ss_y*2, 60, 20)
self.form_finder2_label=QtWidgets.QLabel('Voltage Step (V)', self)
self.form_finder2_label.setGeometry(ss_x, offset_ssl_y+(ss_y*2)-15, 100, 20)
self.form_finder2.hide()
self.form_finder2_label.hide()

self.form_finder3 = QtWidgets.QLineEdit(self)
self.form_finder3.setText("3")
self.form_finder3.setGeometry(ss_x, offset_ss_y+ss_y*3, 60, 20)
self.form_finder3_label=QtWidgets.QLabel('Voltage max (V)', self)
self.form_finder3_label.setGeometry(ss_x, offset_ssl_y+(ss_y*3)-15, 100, 20)
self.form_finder3.hide()
self.form_finder3_label.hide()

self.form_finder4 = QtWidgets.QLineEdit(self)
self.form_finder4.setText("100")
self.form_finder4.setGeometry(ss_x, offset_ss_y+ss_y*4, 60, 20)
self.form_finder4_label=QtWidgets.QLabel('Pulse width min (us)', self)
self.form_finder4_label.setGeometry(ss_x, offset_ssl_y+(ss_y*4)-15, 100, 20)
self.form_finder4.hide()
self.form_finder4_label.hide()

self.form_finder5 = QtWidgets.QLineEdit(self)
self.form_finder5.setText("100")
self.form_finder5.setGeometry(ss_x, offset_ss_y+ss_y*5, 60, 20)
self.form_finder5_label=QtWidgets.QLabel('Pulse width step (%)', self)
self.form_finder5_label.setGeometry(ss_x, offset_ssl_y+(ss_y*5)-15, 100, 20)
self.form_finder5.hide()
self.form_finder5_label.hide()

self.form_finder6 = QtWidgets.QLineEdit(self)
self.form_finder6.setText("1000")
self.form_finder6.setGeometry(ss_x, offset_ss_y+ss_y*6, 60, 20)
self.form_finder6_label=QtWidgets.QLabel('Pulse width max (us)', self)
self.form_finder6_label.setGeometry(ss_x, offset_ssl_y+(ss_y*6)-15, 100, 20)
self.form_finder6.hide()
self.form_finder6_label.hide()

self.form_finder7 = QtWidgets.QLineEdit(self)
self.form_finder7.setText("10")
self.form_finder7.setGeometry(ss_x, offset_ss_y+ss_y*7, 60, 20)
self.form_finder7_label=QtWidgets.QLabel('Interpulse time (ms)', self)
self.form_finder7_label.setGeometry(ss_x, offset_ssl_y+(ss_y*7)-15, 100, 20)
self.form_finder7.hide()
self.form_finder7_label.hide()

self.form_finder8 = QtWidgets.QLineEdit(self)
self.form_finder8.setText("1")
self.form_finder8.setGeometry(ss_x, offset_ss_y+ss_y*8, 60, 20)
self.form_finder8_label=QtWidgets.QLabel('Nr. of pulses', self)
self.form_finder8_label.setGeometry(ss_x, offset_ssl_y+(ss_y*8)-15, 100, 20)
self.form_finder8.hide()
self.form_finder8_label.hide()

self.form_finder9 = QtWidgets.QLineEdit(self)
self.form_finder9.setText("1000")
self.form_finder9.setGeometry(ss_x, offset_ss_y+ss_y*9, 60, 20)
self.form_finder9_label=QtWidgets.QLabel('Resistance threshold', self)
self.form_finder9_label.setGeometry(ss_x, offset_ssl_y+(ss_y*9)-15, 100, 20)
self.form_finder9.hide()
self.form_finder9_label.hide()

self.form_finder10 = QtWidgets.QLineEdit(self)
self.form_finder10.setText("10")
self.form_finder10.setGeometry(ss_x, offset_ss_y+ss_y*10, 60, 20)
self.form_finder10_label=QtWidgets.QLabel('Resistance Threshold (%)', self)
self.form_finder10_label.setGeometry(ss_x, offset_ssl_y+(ss_y*10)-15, 100, 20)
self.form_finder10.hide()
self.form_finder10_label.hide()

self.form_finder_combo1_label=QtWidgets.QLabel('Series Resistance', self)
self.form_finder_combo1_label.setGeometry(ss_x+110, offset_ss_y+ss_y-17, 100, 20)
self.form_finder_combo1=QtWidgets.QComboBox(self)
self.form_finder_combo1.setGeometry(ss_x+110, offset_ss_y+ss_y, 60, 20)
self.form_finder_combo1.addItem('None', 7)
self.form_finder_combo1.addItem('1kohm', 1)
self.form_finder_combo1.addItem('10kohm', 2)
self.form_finder_combo1.addItem('100kohm', 3)
self.form_finder_combo1.addItem('1Mohm', 4)
self.form_finder_combo1_label.hide()
self.form_finder_combo1.hide()

self.form_finder_combo2_label=QtWidgets.QLabel('PW progression', self)
self.form_finder_combo2_label.setGeometry(ss_x+110, offset_ss_y+(ss_y*2)-17, 100, 20)
self.form_finder_combo2=QtWidgets.QComboBox(self)
self.form_finder_combo2.setGeometry(ss_x+110, offset_ss_y+(ss_y*2), 60, 20)
self.form_finder_combo2.addItem("Multiplicative", {"job": 14, "mode": 0})
self.form_finder_combo2.addItem("Linear", {"job": 141, "mode": 1})
self.form_finder_combo2.setEnabled(True)
self.form_finder_combo2_label.hide()
self.form_finder_combo2.hide()

    
self.CB_form_finder1 = QtWidgets.QCheckBox(self)
self.CB_form_finder1.setChecked(False)
self.CB_form_finder1.setGeometry(QtCore.QRect(ss_x+110, offset_ss_y+(ss_y*3), 100, 20))
self.CB_form_finder1_label=QtWidgets.QLabel('Negative\n amplitude', self)
self.CB_form_finder1_label.setGeometry(ss_x+130, offset_ss_y+(ss_y*3), 100, 30)
self.CB_form_finder1.hide()
self.CB_form_finder1_label.hide()

self.CB_form_finder2 = QtWidgets.QCheckBox(self)
self.CB_form_finder2.setChecked(False)
self.CB_form_finder2.setGeometry(QtCore.QRect(ss_x+110, offset_ss_y+(ss_y*4), 100, 20))
self.CB_form_finder2_label=QtWidgets.QLabel('Use Rthr (%)', self)
self.CB_form_finder2_label.setGeometry(ss_x+130, offset_ss_y+(ss_y*4), 100, 30)
self.CB_form_finder2.hide()
self.CB_form_finder2_label.hide()

