
#signals
#self.lcd_signal=pyqtSignal(object)

# "apply" push bottons for readings
hbox = QtWidgets.QHBoxLayout()
self.doOne = QtWidgets.QPushButton('Apply to One')
self.doRange = QtWidgets.QPushButton('Apply to Range')
self.doAll = QtWidgets.QPushButton('Apply to All')
hbox.addWidget(self.doOne)
hbox.addWidget(self.doRange)
hbox.addWidget(self.doAll)
hbox.addWidget(self.doAll)

# lcd screen
self.my_location_label = QLabel('Current site:', self)
self.my_location_label.setGeometry(0, 230, 100, 30)
self.location_label = QLabel('...', self)
self.location_label.setGeometry(0, 245, 120, 20)
self.timer = QTimer()
self.timer.timeout.connect(self.lcd_site)
self.timer.start(100)
self.lcd_site()




# Spinboxes
# spinbox label
self.spinBox_anyrow_label = QLabel('Read One Row', self)
self.spinBox_anyrow_label.setGeometry(0, 30, 80, 20)
# spinbox row
self.spinBox_anyrow = QtWidgets.QSpinBox(self)
self.spinBox_anyrow.setGeometry(QtCore.QRect(20, 50, 42, 22))
self.spinBox_anyrow.setMaximum(config.row_size)
self.spinBox_anyrow.setSingleStep(1)
self.spinBox_anyrow.setObjectName("spinBox")
# Spinboxes read row range
# spinbox label
self.spinBox_rowrange_label = QLabel('Read Row Range', self)
self.spinBox_rowrange_label.setGeometry(0, 75, 90, 20)
# spinbox "from" label
self.spinBox_rowrange_label = QLabel('from', self)
self.spinBox_rowrange_label.setGeometry(20, 90, 90, 20)
# spinbox "to" label
self.spinBox_rowrange_label = QLabel('to', self)
self.spinBox_rowrange_label.setGeometry(70, 90, 90, 20)
# spinbox "from"
self.spinBox_rowrangeto = QtWidgets.QSpinBox(self)
self.spinBox_rowrangeto.setGeometry(QtCore.QRect(20, 110, 42, 22))
self.spinBox_rowrangeto.setMaximum(config.row_size)
self.spinBox_rowrangeto.setSingleStep(1)
self.spinBox_rowrangeto.setObjectName("rowrangeto")
# spinbox "to"
self.spinBox_rowrangefrom = QtWidgets.QSpinBox(self)
self.spinBox_rowrangefrom.setGeometry(QtCore.QRect(70, 110, 42, 22))
self.spinBox_rowrangefrom.setMaximum(config.row_size)
self.spinBox_rowrangefrom.setSingleStep(1)
self.spinBox_rowrangefrom.setObjectName("rowrangefrom")

# spinbox movestep
self.spinBox_movestep_label = QLabel('Move Unit', self)
self.spinBox_movestep_label.setGeometry(147, 144, 60, 20)
self.spinBox_movestep = QtWidgets.QSpinBox(self)
self.spinBox_movestep.setGeometry(QtCore.QRect(155, 160, 30, 22))
self.spinBox_movestep.setMaximum(config.row_size)
self.spinBox_movestep.setSingleStep(1)
self.spinBox_movestep.setValue(1)
self.spinBox_movestep.setObjectName("movestep")

# Radio Buttons
self.RB_anyrow = QtWidgets.QRadioButton(self)
self.RB_anyrow.setChecked(False)
self.RB_anyrow.setGeometry(QtCore.QRect(0, 50, 15, 15))
self.RB_rowrange = QtWidgets.QRadioButton(self)
self.RB_rowrange.setGeometry(QtCore.QRect(0, 102, 15, 15))
self.RB_fullwafer = QLabel('Read Full Wafer', self)
self.RB_fullwafer.setGeometry(0, 135, 80, 20)
self.RB_fullwafer = QtWidgets.QRadioButton(self)
self.RB_fullwafer.setGeometry(QtCore.QRect(0, 155, 15, 15))
self.RB_desired = QLabel('Read Selected Dice', self)
self.RB_desired.setGeometry(0, 170, 100, 20)
self.RB_desired = QtWidgets.QRadioButton(self)
self.RB_desired.setChecked(False)
self.RB_desired.setGeometry(QtCore.QRect(0, 190, 15, 15))
self.manual = QtWidgets.QRadioButton(self)
self.manual.setChecked(True)
self.manual.setGeometry(QtCore.QRect(120, 110, 15, 15))

# Checkboxes
# subdice checkboxes
self.subdice_label = QLabel('Subdies Map', self)
self.subdice_label.setGeometry(QtCore.QRect(130, 33, 100, 15))
self.CB_00 = QtWidgets.QCheckBox(self)
self.CB_00.setChecked(True)
self.CB_00.setGeometry(QtCore.QRect(130, 50, 15, 15))
self.CB_00_label = QLabel('S1', self)
self.CB_00_label.setGeometry(145, 50, 15, 15)
self.CB_01 = QtWidgets.QCheckBox(self)
self.CB_01.setGeometry(QtCore.QRect(160, 50, 15, 15))
self.CB_01_label = QLabel('S2', self)
self.CB_01_label.setGeometry(175, 50, 15, 15)
self.CB_02 = QtWidgets.QCheckBox(self)
self.CB_02.setGeometry(QtCore.QRect(190, 50, 15, 15))
self.CB_02_label = QLabel('S3', self)
self.CB_02_label.setGeometry(205, 50, 15, 15)
self.CB_10 = QtWidgets.QCheckBox(self)
self.CB_10.setGeometry(QtCore.QRect(130, 65, 15, 15))
self.CB_10_label = QLabel('S4', self)
self.CB_10_label.setGeometry(145, 65, 15, 15)
self.CB_11 = QtWidgets.QCheckBox(self)
self.CB_11.setGeometry(QtCore.QRect(160, 65, 15, 15))
self.CB_11_label = QLabel('S5', self)
self.CB_11_label.setGeometry(175, 65, 15, 15)
self.CB_12 = QtWidgets.QCheckBox(self)
self.CB_12.setGeometry(QtCore.QRect(190, 65, 15, 15))
self.CB_12_label = QLabel('S6', self)
self.CB_12_label.setGeometry(205, 65, 15, 15)
self.CB_20 = QtWidgets.QCheckBox(self)
self.CB_20.setGeometry(QtCore.QRect(130, 80, 15, 15))
self.CB_20_label = QLabel('S7', self)
self.CB_20_label.setGeometry(145, 80, 15, 15)
self.CB_21 = QtWidgets.QCheckBox(self)
self.CB_21.setGeometry(QtCore.QRect(160, 80, 15, 15))
self.CB_21_label = QLabel('S8', self)
self.CB_21_label.setGeometry(175, 80, 15, 15)
self.CB_22 = QtWidgets.QCheckBox(self)
self.CB_22.setGeometry(QtCore.QRect(190, 80, 15, 15))
self.CB_22_label = QLabel('S9', self)
self.CB_22_label.setGeometry(205, 80, 15, 15)

#functional checkbox (keep it hidden)
self.CB_func1 = QtWidgets.QCheckBox(self)
#self.CB_22.setGeometry(QtCore.QRect(190, 80, 15, 15))

# skip odd checkbox
self.skip_odd_label = QtWidgets.QLabel('Skip odd dice:', self)
self.skip_odd_label.setGeometry(0, 205, 100, 20)
self.skip_odd = QtWidgets.QCheckBox(self)
self.skip_odd.setGeometry(70, 205, 100, 20)

# Push Buttons
# manual control
self.move_up_label = QtWidgets.QLabel('Manual Control', self)
self.move_up_label.setGeometry(140, 110, 80, 20)
self.move_up = QtWidgets.QPushButton('up', self)
self.move_up.setGeometry(150, 130, 40, 20)
self.move_down = QtWidgets.QPushButton('down', self)
self.move_down.setGeometry(150, 190, 40, 20)
self.move_left = QtWidgets.QPushButton('L', self)
self.move_left.setGeometry(120, 160, 30, 20)
self.move_right = QtWidgets.QPushButton('R', self)
self.move_right.setGeometry(190, 160, 30, 20)
self.move_contact = QtWidgets.QPushButton('C', self)
self.move_contact.setGeometry(130, 215, 20, 20)
self.move_separation = QtWidgets.QPushButton('S', self)
self.move_separation.setGeometry(150, 215, 20, 20)
self.set_index_dice = QtWidgets.QPushButton('Di', self)
self.set_index_dice.setGeometry(170, 215, 20, 20)
self.set_index_subdice = QtWidgets.QPushButton('di', self)
self.set_index_subdice.setGeometry(190, 215, 20, 20)

self.button_map=QtWidgets.QPushButton('Map', self)
self.button_map.setGeometry(130, 240, 80, 40)



#self.goto_die_box = QtWidgets.QLineEdit(self)
#self.goto_die_box.setGeometry(130, 250, 40, 20)
#self.goto_die_box.setText("1")
#self.goto_die_box_label = QtWidgets.QLabel('D', self)
#self.goto_die_box_label.setGeometry(121, 250, 15, 15)

# self.goto_subdie_box = QtWidgets.QLineEdit(self)
# self.goto_subdie_box.setGeometry(165, 250, 25, 20)
# self.goto_subdie_box.setText("1")
# self.goto_die_box_label = QtWidgets.QLabel('S', self)
# self.goto_die_box_label.setGeometry(158, 250, 15, 15)

self.set_reference = QtWidgets.QPushButton('Set Ref', self)
self.set_reference.setGeometry(530, 40, 60, 25)
self.load_reference = QtWidgets.QPushButton('Load Ref', self)
self.load_reference.setGeometry(460, 40, 60, 25)
self.show_fct1 = QtWidgets.QPushButton('fct1', self)
self.show_fct1.setGeometry(530, 70, 60, 25)
self.show_fct2 = QtWidgets.QPushButton('fct2', self)
self.show_fct2.setGeometry(530, 100, 60, 25)
self.show_fct3 = QtWidgets.QPushButton('fct3', self)
self.show_fct3.setGeometry(530, 130, 60, 25)
self.show_fct4 = QtWidgets.QPushButton('fct4', self)
self.show_fct4.setGeometry(530, 160, 60, 25)
self.show_fct5 = QtWidgets.QPushButton('fct5', self)
self.show_fct5.setGeometry(530, 190, 60, 25)
self.show_fct6 = QtWidgets.QPushButton('fct6', self)
self.show_fct6.setGeometry(530, 220, 60, 25)
self.show_fct7 = QtWidgets.QPushButton('fct7', self)
self.show_fct7.setGeometry(530, 250, 60, 25)

layout.addItem(QtWidgets.QSpacerItem(40, 10, \
                                     QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding))
layout.addLayout(hbox)
self.setLayout(layout)

# selection module combo
self.fct1_combo = QtWidgets.QComboBox(self)
self.fct1_combo.setGeometry(440, 70, 80, 20)
self.fct1_combo.addItem(" ")
self.fct1_combo.addItem("Form Finder")
self.fct1_combo.addItem("Switch Seeker")
self.fct1_combo.addItem("Retention")
self.fct1_combo.addItem("Converge")
self.fct1_combo.addItem("CurveTracer")
self.fct1_combo.addItem("ParameterFit")
self.fct1_combo.addItem("RILForming")
self.fct1_combo.addItem("Uniformity")

self.fct2_combo = QtWidgets.QComboBox(self)
self.fct2_combo.setGeometry(440, 100, 80, 20)
self.fct2_combo.addItem(" ")
self.fct2_combo.addItem("Form Finder")
self.fct2_combo.addItem("Switch Seeker")
self.fct2_combo.addItem("Retention")
self.fct2_combo.addItem("Converge")
self.fct2_combo.addItem("CurveTracer")
self.fct2_combo.addItem("ParameterFit")
self.fct2_combo.addItem("RILForming")
self.fct2_combo.addItem("Uniformity")

self.fct3_combo = QtWidgets.QComboBox(self)
self.fct3_combo.setGeometry(440, 130, 80, 20)
self.fct3_combo.addItem(" ")
self.fct3_combo.addItem("Form Finder")
self.fct3_combo.addItem("Switch Seeker")
self.fct3_combo.addItem("Retention")
self.fct3_combo.addItem("Converge")
self.fct3_combo.addItem("CurveTracer")
self.fct3_combo.addItem("ParameterFit")
self.fct3_combo.addItem("RILForming")
self.fct3_combo.addItem("Uniformity")

self.fct4_combo = QtWidgets.QComboBox(self)
self.fct4_combo.setGeometry(440, 160, 80, 20)
self.fct4_combo.addItem(" ")
self.fct4_combo.addItem("Form Finder")
self.fct4_combo.addItem("Switch Seeker")
self.fct4_combo.addItem("Retention")
self.fct4_combo.addItem("Converge")
self.fct4_combo.addItem("CurveTracer")
self.fct4_combo.addItem("ParameterFit")
self.fct4_combo.addItem("RILForming")
self.fct4_combo.addItem("Uniformity")
self.hidden = True

self.fct5_combo = QtWidgets.QComboBox(self)
self.fct5_combo.setGeometry(440, 190, 80, 20)
self.fct5_combo.addItem(" ")
self.fct5_combo.addItem("Form Finder")
self.fct5_combo.addItem("Switch Seeker")
self.fct5_combo.addItem("Retention")
self.fct5_combo.addItem("Converge")
self.fct5_combo.addItem("CurveTracer")
self.fct5_combo.addItem("ParameterFit")
self.fct5_combo.addItem("RILForming")
self.fct5_combo.addItem("Uniformity")

self.fct6_combo = QtWidgets.QComboBox(self)
self.fct6_combo.setGeometry(440, 220, 80, 20)
self.fct6_combo.addItem(" ")
self.fct6_combo.addItem("Form Finder")
self.fct6_combo.addItem("Switch Seeker")
self.fct6_combo.addItem("Retention")
self.fct6_combo.addItem("Converge")
self.fct6_combo.addItem("CurveTracer")
self.fct6_combo.addItem("ParameterFit")
self.fct6_combo.addItem("RILForming")
self.fct6_combo.addItem("Uniformity")

self.fct7_combo = QtWidgets.QComboBox(self)
self.fct7_combo.setGeometry(440, 250, 80, 20)
self.fct7_combo.addItem(" ")
self.fct7_combo.addItem("Form Finder")
self.fct7_combo.addItem("Switch Seeker")
self.fct7_combo.addItem("Retention")
self.fct7_combo.addItem("Converge")
self.fct7_combo.addItem("CurveTracer")
self.fct7_combo.addItem("ParameterFit")
self.fct7_combo.addItem("RILForming")
self.fct7_combo.addItem("Uniformity")

#self.fct7 = QtWidgets.QTextEdit(self)
#self.fct7.setText("4,12,14,21,23,25,34,36,38,46,48,50,61,63,65,75,77,79,81,91,93,95")
#self.fct7.setGeometry(0, 300, 100, 100)
#self.fct7_label = QLabel("Select dice:", self)
#self.fct7_label.setGeometry(0, 240, 100, 100)

self.fct8 = QtWidgets.QLineEdit(self)
self.fct8.setText("10")
self.fct8.setGeometry(440, 290, 40, 20)
self.fct8_label = QLabel("Trig. min ratio(%):", self)
self.fct8_label.setGeometry(440, 270, 80, 20)

self.fct9 = QtWidgets.QLineEdit(self)
self.fct9.setText("20")
self.fct9.setGeometry(440, 330, 40, 20)
self.fct9_label = QLabel("Trig. max ratio(%):", self)
self.fct9_label.setGeometry(440, 310, 80, 20)

self.repeat_fct = QtWidgets.QLineEdit(self)
self.repeat_fct.setText("1")
self.repeat_fct.setGeometry(530, 290, 40, 20)
self.repeat_fct_label = QLabel("Repeat each fct:", self)
self.repeat_fct_label.setGeometry(530, 270, 150, 20)

self.repeat_chain = QtWidgets.QLineEdit(self)
self.repeat_chain.setText("1")
self.repeat_chain.setGeometry(530, 330, 40, 20)
self.repeat_chain_label = QLabel("Repeat each chain:", self)
self.repeat_chain_label.setGeometry(530, 310, 150, 20)

#self.goto_site = QtWidgets.QPushButton('Go', self)
#self.goto_site.setGeometry(200, 250, 30, 22)

