ss_x=240
ss_y=35
offset_ss_x=0
offset_ss_y=20
offset_ssl_x=0
offset_ssl_y=18

self.switch_seek1 = QtWidgets.QLineEdit(self)
self.switch_seek1.setText("5")
self.switch_seek1.setGeometry(ss_x, offset_ss_y+ss_y, 60, 20)
self.switch_seek1_label=QtWidgets.QLabel('Reads in Trailed card', self)
self.switch_seek1_label.setGeometry(ss_x, offset_ssl_y+ss_y-15, 100, 20)
self.switch_seek1.hide()
self.switch_seek1_label.hide()

self.switch_seek2 = QtWidgets.QLineEdit(self)
self.switch_seek2.setText("10")
self.switch_seek2.setGeometry(ss_x, offset_ss_y+ss_y*2, 60, 20)
self.switch_seek2_label=QtWidgets.QLabel('Programming Pulses', self)
self.switch_seek2_label.setGeometry(ss_x, offset_ssl_y+(ss_y*2)-15, 100, 20)
self.switch_seek2.hide()
self.switch_seek2_label.hide()

self.switch_seek3 = QtWidgets.QLineEdit(self)
self.switch_seek3.setText("0.1")
self.switch_seek3.setGeometry(ss_x, offset_ss_y+ss_y*3, 60, 20)
self.switch_seek3_label=QtWidgets.QLabel('Pulse duration(ms)', self)
self.switch_seek3_label.setGeometry(ss_x, offset_ssl_y+(ss_y*3)-15, 100, 20)
self.switch_seek3.hide()
self.switch_seek3_label.hide()

self.switch_seek4 = QtWidgets.QLineEdit(self)
self.switch_seek4.setText("1.5")
self.switch_seek4.setGeometry(ss_x, offset_ss_y+ss_y*4, 60, 20)
self.switch_seek4_label=QtWidgets.QLabel('Voltage min(V)', self)
self.switch_seek4_label.setGeometry(ss_x, offset_ssl_y+(ss_y*4)-15, 100, 20)
self.switch_seek4.hide()
self.switch_seek4_label.hide()

self.switch_seek5 = QtWidgets.QLineEdit(self)
self.switch_seek5.setText("0.05")
self.switch_seek5.setGeometry(ss_x, offset_ss_y+ss_y*5, 60, 20)
self.switch_seek5_label=QtWidgets.QLabel('Voltage step(V)', self)
self.switch_seek5_label.setGeometry(ss_x, offset_ssl_y+(ss_y*5)-15, 100, 20)
self.switch_seek5.hide()
self.switch_seek5_label.hide()

self.switch_seek6 = QtWidgets.QLineEdit(self)
self.switch_seek6.setText("4")
self.switch_seek6.setGeometry(ss_x, offset_ss_y+ss_y*6, 60, 20)
self.switch_seek6_label=QtWidgets.QLabel('Voltage max(V)', self)
self.switch_seek6_label.setGeometry(ss_x, offset_ssl_y+(ss_y*6)-15, 100, 20)
self.switch_seek6.hide()
self.switch_seek6_label.hide()

self.switch_seek7 = QtWidgets.QLineEdit(self)
self.switch_seek7.setText("5")
self.switch_seek7.setGeometry(ss_x, offset_ss_y+ss_y*7, 60, 20)
self.switch_seek7_label=QtWidgets.QLabel('Max switching cycles', self)
self.switch_seek7_label.setGeometry(ss_x, offset_ssl_y+(ss_y*7)-15, 100, 20)
self.switch_seek7.hide()
self.switch_seek7_label.hide()

self.switch_seek8 = QtWidgets.QLineEdit(self)
self.switch_seek8.setText("30")
self.switch_seek8.setGeometry(ss_x, offset_ss_y+ss_y*8, 60, 20)
self.switch_seek8_label=QtWidgets.QLabel('Tolerance band(%)', self)
self.switch_seek8_label.setGeometry(ss_x, offset_ssl_y+(ss_y*8)-15, 100, 20)
self.switch_seek8.hide()
self.switch_seek8_label.hide()

self.switch_seek9 = QtWidgets.QLineEdit(self)
self.switch_seek9.setText("1")
self.switch_seek9.setGeometry(ss_x, offset_ss_y+ss_y*9, 60, 20)
self.switch_seek9_label=QtWidgets.QLabel('Interpulse time(ms)', self)
self.switch_seek9_label.setGeometry(ss_x, offset_ssl_y+(ss_y*9)-15, 100, 20)
self.switch_seek9.hide()
self.switch_seek9_label.hide()

self.switch_seek10 = QtWidgets.QLineEdit(self)
self.switch_seek10.setText("1")
self.switch_seek10.setGeometry(ss_x, offset_ss_y+ss_y*10, 60, 20)
self.switch_seek10_label=QtWidgets.QLabel('Resistance Threshold', self)
self.switch_seek10_label.setGeometry(ss_x, offset_ssl_y+(ss_y*10)-15, 100, 20)
self.switch_seek10.hide()
self.switch_seek10_label.hide()

self.switch_seek_combo1_label=QtWidgets.QLabel('Seeker algorithm', self)
self.switch_seek_combo1_label.setGeometry(ss_x+110, offset_ss_y+ss_y-17, 100, 20)
self.switch_seek_combo1=QtWidgets.QComboBox(self)
self.switch_seek_combo1.setGeometry(ss_x+110, offset_ss_y+ss_y, 60, 20)
self.switch_seek_combo1.addItem("Fast", 15)
self.switch_seek_combo1.addItem("Slow", 152)
self.switch_seek_combo1_label.hide()
self.switch_seek_combo1.hide()

self.switch_seek_combo2_label=QtWidgets.QLabel('Stage II polarity', self)
self.switch_seek_combo2_label.setGeometry(ss_x+110, offset_ss_y+(ss_y*2)-17, 100, 20)
self.switch_seek_combo2=QtWidgets.QComboBox(self)
self.switch_seek_combo2.setGeometry(ss_x+110, offset_ss_y+(ss_y*2), 60, 20)
self.switch_seek_combo2.addItem("(+) Positive")
self.switch_seek_combo2.addItem("(-) Negative")
self.switch_seek_combo2.setEnabled(False)
self.switch_seek_combo2_label.hide()
self.switch_seek_combo2.hide()

    
self.CB_skip_stage1 = QtWidgets.QCheckBox(self)
self.CB_skip_stage1.setChecked(False)
self.CB_skip_stage1.setGeometry(QtCore.QRect(ss_x+110, offset_ss_y+(ss_y*3), 100, 20))
self.CB_skip_stage1_label=QtWidgets.QLabel('Skip Stage I', self)
self.CB_skip_stage1_label.setGeometry(ss_x+130, offset_ss_y+(ss_y*3), 100, 20)
self.CB_skip_stage1.hide()
self.CB_skip_stage1_label.hide()

self.CB_read_after = QtWidgets.QCheckBox(self)
self.CB_read_after.setChecked(False)
self.CB_read_after.setGeometry(QtCore.QRect(ss_x+110, offset_ss_y+(ss_y*4), 100, 20))
self.CB_read_after_label=QtWidgets.QLabel('Read after \n pulse', self)
self.CB_read_after_label.setGeometry(ss_x+130, offset_ss_y+(ss_y*4), 100, 30)
self.CB_read_after.hide()
self.CB_read_after_label.hide()

